### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by zhushaojun65** [redblobgames/mapgen4#1]
Hi, please help me
when i run the last cmd 'npm run build', the console will show me 

`Error: ENOENT: no such file or directory, lstat 'D:\work\Git\mapgen4\node_modules\@redblobgames\dual-mesh\dist\dual-mesh.js'
    at Error (native)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @redblobgames/mapgen4-ui@1.0.0 build: `browserify mapgen4.js -g uglifyify -o build/_bundle.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @redblobgames/mapgen4-ui@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zsj\AppData\Roaming\npm-cache\_logs\2019-09-23T03_46_10_224Z-debug.log`

**Comment by redblobgames** [comment]
Oh, interesting. I will investigate.

**Comment by redblobgames** [comment]
Quick workaround: edit `node_modules/@redblobgames/dual-mesh/package.json` and remove the line that says `"browser": "dist/dual-mesh.js",`. 

I don't quite understand the best way to use package.json so I am going to remove that line.

**Comment by zhushaojun65** [comment]
@redblobgames 
thx for you help, i had build success, but there are some problems
when i run `python -m http.server 8000` (in python3 ` SimpleHTTPServer` rename to `http.server`), it seems normal boot, but when i visit http://localhost:8000/embed.html in my browser(`chrome`), i get error: `Uncaught (in promise) RangeError: byte length of Uint16Array should be a multiple of 2
    at new Uint16Array (<anonymous>)
    at extractPoints (_bundle.js:17)
    at choosePoints (_bundle.js:17)
    at async Object.makeMesh (_bundle.js:17)`

**Comment by zhushaojun65** [comment]
> @redblobgames
> thx for you help, i had build success, but there are some problems
> when i run `python -m http.server 8000` (in python3 ` SimpleHTTPServer` rename to `http.server`), it seems normal boot, but when i visit http://localhost:8000/embed.html in my browser(`chrome`), i get error: `Uncaught (in promise) RangeError: byte length of Uint16Array should be a multiple of 2 at new Uint16Array (<anonymous>) at extractPoints (_bundle.js:17) at choosePoints (_bundle.js:17) at async Object.makeMesh (_bundle.js:17)`

i know where is the problem, in step `make build/points-5.data`, the points count may be a base, but uint16Array should be a multiple of 2

**Comment by redblobgames** [comment]
Wow, this is weird. It worked for me in Firefox, and then it worked for me in Chrome, and then I reloaded in both browsers and it stopped working in Chrome, continued working in Firefox, and then it crashed my entire computer :(

**Comment by redblobgames** [comment]
After I rebooted the computer it seems to be working for me in both Chrome and Firefox. There may still be a bug somewhere but I am not sure how to find it :(

**Comment by zhushaojun65** [comment]
@redblobgames when i get error, I print the point count in build/points-5.data, it is really a base. so i think may be the problem make by generate-points.js

**Comment by redblobgames** [comment]
I am not sure what you mean by "a base". You can try downloading https://www.redblobgames.com/maps/mapgen4/build/points-5.data — is it the same as your points-5.data?

**Comment by zhushaojun65** [comment]
@redblobgames sorry, "a base" mean "can't be divided exactly by 2"
