### ISSUE TITLE
[Question] How to change river color?

### ISSUE THREAD

**Issue by dglee2592** [redblobgames/mapgen4#9]
Hello, 

I really impressed with this and thank you so much for your sharing this wonderful project.

I tried your code as instructed, and everything works perfect!!! Great!!

Can I ask one thing? How to change the River color? I was looking colormap.js and render.js and tried several changes, but still failed to change the river color...
I'm now trying to extract height map from your mapgen4 image but river color gave me some problem... I want to make river color more dark.... (close to rgb 50,50,50)

Any advice or hint will be highly appreciate!!!
Thanks for this great job!!!

**Comment by redblobgames** [comment]
Hi dglee, thank you! colormap.js is for the terrain but the rivers are in a shader. Look in render.js and try changing the color in this function:
```js
const drawRivers = regl({
    frag: `
precision mediump float;
uniform sampler2D u_rivertexturemap;
varying vec2 v_uv;
const vec3 blue = vec3(0.2, 0.5, 0.7);
void main() {
   vec4 color = texture2D(u_rivertexturemap, v_uv);
   gl_FragColor = vec4(blue * color.a, color.a);
   // gl_FragColor = color;
}`,
```

**Comment by dglee2592** [comment]
Oh it was there! works perfect! Thank you so much!!
